apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustersubscription-controller
  namespace: razee
  labels:
    razee/watch-resource: "lite"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustersubscription-controller
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clustersubscription-controller
        razee/watch-resource: "lite"
      name: clustersubscription-controller
    spec:
      serviceAccountName: razeedeploy-sa
      containers:
      - image: "cs:latest"
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: 75Mi
            cpu: 40m
        env:
          - name: RAZEE_ORG_KEY
            valueFrom:
              configMapKeyRef:
                name: razee-org-key
                key: RAZEE_ORG_KEY
          - name: RAZEE_TAGS 
            valueFrom:
              configMapKeyRef:
                name: razee-tags
                key: RAZEE_TAGS
          - name: RAZEE_API 
            valueFrom:
              configMapKeyRef:
                name: razee-api
                key: RAZEE_API
        imagePullPolicy: Never
        name: clustersubscription-controller
